# Vexora IT Solutions - Upptime Configuration

# GitHub Details
owner: vexoraitsolution # Your GitHub Organization or Username
repo: status-page           # The name of your GitHub repository

# Endpoints to Monitor
sites:
  - name: Vexora Main Website
    url: https://vexorait.com
   # - name: VexoraTap
   #  url: https://tap.vexorait.com   

  # - name: Private Server Check
  #   url: $SECRET_SITE        # Optional: Private URL fetched from GitHub Secrets

# Public Status Page Settings
status-website:
  cname: status.vexorait.com # Custom Domain CNAME
  logoUrl: https://vexorait.com/assets/logo.png # URL of your company logo
  faviconUrl: https://vexorait.com/assets/favicon.ico
  name: Vexora System Status
  
  introTitle: "**Vexora Systems & API Live Status**"
  introMessage: Welcome to the official real-time status page for **Vexora IT Solutions**. Here you can monitor the uptime, response times, and incident reports for our API Gateways and core infrastructure.
  
  # Navigation Bar Links
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://vexorait.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
